#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: user-service
#      username: app
#      password: 123123
#      uri: mongodb://app:123123@localhost:27017/user-service
#      authenticationDatabase: user-service

#spring:
#  data:
#    mongodb:
#      uri: mongodb://us-app:123456@localhost:27017/userService
